CREATE TABLE R_URL (
	CODE				SMALLINT			NOT NULL,
	WEB_NAME_CODE		SMALLINT			NOT NULL,
	DESCRIPTION			VARCHAR(250)		NOT NULL,
	WEB_TYPE_CODE		SMALLINT			NOT NULL,
	ACTIVE				CHAR(1)				NOT NULL,
	CONSTRAINT PK_URL PRIMARY KEY (CODE)
);

CREATE TABLE R_WEB_TYPE (
	CODE				SMALLINT 			NOT NULL,
	DESCRIPTION			VARCHAR(250)		NOT NULL,
	CONSTRAINT PK_WEB_TYPE PRIMARY KEY (CODE)
);

CREATE TABLE R_WEB_NAME (
	CODE				SMALLINT 			NOT NULL,
	DESCRIPTION			VARCHAR(250)		NOT NULL,
	CONSTRAINT PK_WEB_NAME PRIMARY KEY (CODE)
);

CREATE TABLE R_USER_LOGIN_TYPE (
	CODE				SMALLINT			NOT NULL,
	DESCRIPTION			VARCHAR(250)		NOT NULL,
	CONSTRAINT PK_USER_LOGIN_TYPE PRIMARY KEY (CODE)
);

CREATE TABLE R_ROLE (
	CODE				SMALLINT			NOT NULL,
	DESCRIPTION			VARCHAR(250)		NOT NULL,
	CONSTRAINT PK_ROLE PRIMARY KEY (CODE)
);