CREATE TABLE E_SEARCHING (
	SEARCHING_ID		INTEGER			NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DESCRIPTION			VARCHAR(200)	NOT NULL,
	USER_ID				INTEGER			NOT NULL,
	CREATE_DATE			TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ACTIVE 				CHAR(1)			NOT NULL CHECK (ACTIVE IN ('Y','N')),
	
	CONSTRAINT FK_E_SEARCHING FOREIGN KEY (USER_ID) REFERENCES E_USER(USER_ID)
);

CREATE TABLE ER_SEACHING_MAP_THAIMTB (
	SEARCHING_ID		INTEGER			NOT NULL,
	THAIMTB_ID			INTEGER			NOT NULL,
	CREATE_DATE			TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	SCORE_HIT			FLOAT			,
	CONSTRAINT PK_ER_SEACHING_MAP_THAIMTB			PRIMARY KEY(SEARCHING_ID, THAIMTB_ID),
	CONSTRAINT FK_SEACHING_MAP_THAIMTB_SEARCHING_ID FOREIGN KEY(SEARCHING_ID) REFERENCES E_SEARCHING(SEARCHING_ID),
	CONSTRAINT FK_SEACHING_MAP_THAIMTB_THAIMTB_ID	FOREIGN KEY(THAIMTB_ID) REFERENCES E_THAIMTB_CONTENT(THAIMTB_ID)
);