CREATE TABLE E_THAIMTB_CONTENT(
	THAIMTB_ID				INTEGER			NOT NULL primary key AUTO_INCREMENT,
	URL_CODE				SMALLINT		NOT NULL,
	DESCRIPTION				VARCHAR(300)	NOT NULL,
	URL_CONTENT_LINK		VARCHAR(250)	NOT NULL,
	DATE_CONTENT_CREATE		VARCHAR(100)	,
	CREATE_DATE				TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP
);