CREATE TABLE E_USER(
	USERNAME			VARCHAR(100)NOT NULL PRIMARY KEY,
	DISPLAY_NAME		VARCHAR(250)NOT NULL,
	TOKEN_UID			VARCHAR(250)NOT NULL,
	CREATE_DATE			TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USER_LOGIN_TYPE		SMALLINT	NOT NULL,
	ACTIVE				CHAR(1) 	NOT NULL CHECK (ACTIVE IN ('Y','N')),
	CONSTRAINT FK_USER_USER_LOGIN_TYPE FOREIGN KEY (USER_LOGIN_TYPE) REFERENCES R_USER_LOGIN_TYPE(CODE)
);

CREATE TABLE E_USER_DEVICE(
	USERNAME			VARCHAR(100)NOT NULL,
	DEVICE_MODEL		VARCHAR(100)NOT NULL,
	OS_TYEP_CODE		SMALLINT	NOT NULL,
	TOEKN_NOTIFICATION	VARCHAR(250)NOT NULL,
	MODIFY_DATE			TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ACTIVE				CHAR(1) 	NOT NULL CHECK (ACTIVE IN ('Y','N')),
	CONSTRAINT PK_USER_DEVICE			PRIMARY KEY (DEVICE_MODEL, USERNAME),
	CONSTRAINT FK_USER_DEVICE_USERNAME FOREIGN KEY (USERNAME) REFERENCES E_USER(USERNAME)
);

CREATE TABLE E_USER_FACEBOOK(
	USERNAME			VARCHAR(100)NOT NULL,
	TOKEN_FACEBOOK		VARCHAR(250)NOT NULL,
	MODIFY_DATE			TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_USER_FACEBOOK			PRIMARY KEY (USERNAME),
	CONSTRAINT FK_USER_FACEBOOK_USERNAME FOREIGN KEY (USERNAME) REFERENCES E_USER(USERNAME)
);

CREATE TABLE ER_USER_ROLE(
	USERNAME			VARCHAR(100)NOT NULL,
	ROLE_CODE			SMALLINT	NOT NULL,
	CONSTRAINT PK_ER_USER_ROLE				PRIMARY KEY (USERNAME, ROLE_CODE),
	CONSTRAINT FK_ER_USER_ROLE_USERNAME		FOREIGN KEY (USERNAME) REFERENCES E_USER(USERNAME),
	CONSTRAINT FK_ER_USER_ROLE_ROLE_CODE	FOREIGN KEY (ROLE_CODE) REFERENCES R_ROLE(CODE)
);

