CREATE TABLE E_CONTENT(
	CONTENT_ID				INTEGER			NOT NULL primary key AUTO_INCREMENT,
	URL_CODE				SMALLINT		NOT NULL,
	FACEBOOK_GROP_CODE		SMALLINT		,
	TITLE					VARCHAR(500)	,
	DESCRIPTION				VARCHAR(1000)	,
	CONTENT_WEB_ID			VARCHAR(200)	NOT NULL,
	URL_CONTENT_LINK		VARCHAR(250)	NOT NULL,
	DATE_CONTENT_CREATE		DATETIME	 	,
	CREATE_DATE				TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP
);