CREATE TABLE E_USER(
	USER_ID					VARCHAR(100)NOT NULL PRIMARY KEY, 
	EMAIL					VARCHAR(100)NOT NULL,
	DISPLAY_NAME			VARCHAR(250)NOT NULL,
	CREATE_DATE				TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USER_LOGIN_TYPE			SMALLINT	NOT NULL,
	ACTIVE					CHAR(1) 	NOT NULL CHECK (ACTIVE IN ('Y','N')),
	CONSTRAINT FK_USER_USER_LOGIN_TYPE FOREIGN KEY (USER_LOGIN_TYPE) REFERENCES R_USER_LOGIN_TYPE(CODE)
);

CREATE TABLE E_USER_DEVICE(
	USER_ID				VARCHAR(100)NOT NULL,
	DEVICE_MODEL		VARCHAR(100)NOT NULL,
	OS_TYPE_CODE		SMALLINT	NOT NULL,
	TOKEN_NOTIFICATION	VARCHAR(250)NOT NULL,
	MODIFY_DATE			TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ACTIVE				CHAR(1) 	NOT NULL CHECK (ACTIVE IN ('Y','N')),
	CONSTRAINT PK_USER_DEVICE			PRIMARY KEY (DEVICE_MODEL, USER_ID),
	CONSTRAINT FK_USER_DEVICE_USER_ID FOREIGN KEY (USER_ID) REFERENCES E_USER(USER_ID)
);

CREATE TABLE E_USER_FACEBOOK(
	USER_ID				VARCHAR(100)NOT NULL,
	FACEBOOK_ID			VARCHAR(100)NOT NULL,
	TOKEN_FACEBOOK		VARCHAR(250),
	MODIFY_DATE			TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_USER_FACEBOOK			PRIMARY KEY (USER_ID),
	CONSTRAINT FK_USER_FACEBOOK_USER_ID  FOREIGN KEY (USER_ID) REFERENCES E_USER(USER_ID)
);

CREATE TABLE ER_USER_ROLE(
	USER_ID				VARCHAR(100)NOT NULL,
	ROLE_CODE			SMALLINT	NOT NULL,
	CONSTRAINT PK_ER_USER_ROLE				PRIMARY KEY (USER_ID, ROLE_CODE),
	CONSTRAINT FK_ER_USER_ROLE_USER_ID		FOREIGN KEY (USER_ID) REFERENCES E_USER(USER_ID),
	CONSTRAINT FK_ER_USER_ROLE_ROLE_CODE	FOREIGN KEY (ROLE_CODE) REFERENCES R_ROLE(CODE)
);

